// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app1.Data;

#nullable disable

namespace app1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408204503_ll")]
    partial class ll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app1.Modle.Categre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategreId");

                    b.ToTable("Categres");
                });

            modelBuilder.Entity("app1.Modle.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("categreid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categreid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("app1.Modle.Categre", b =>
                {
                    b.HasOne("app1.Modle.Categre", null)
                        .WithMany("categres")
                        .HasForeignKey("CategreId");
                });

            modelBuilder.Entity("app1.Modle.Product", b =>
                {
                    b.HasOne("app1.Modle.Categre", "categre")
                        .WithMany()
                        .HasForeignKey("categreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categre");
                });

            modelBuilder.Entity("app1.Modle.Categre", b =>
                {
                    b.Navigation("categres");
                });
#pragma warning restore 612, 618
        }
    }
}
